# Generated by Django 5.1.4 on 2025-01-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='faces/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
